name: mirror

#on: ['push']


on:
  push:
    branches:
      - master
  schedule:
    # daily on github default branch
    - cron:  '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Run Mirror Script
        run: python mirror_to_github.py
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
