name: mirror docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/mirror-docker.yaml"
      - package.json
      - yarn.lock
  schedule:
    - cron: "0 4 * * *"

jobs:
  dockerhub-mirror:
    strategy:
      fail-fast: false
      matrix:
        include:
          - src: "ghcr.io/bangumi/server-private"
            dest: "trim21/bangumi-server-private"
            tags: "^(master-.*|v.*)$"
            overwrite: "^(latest|master)$"

          - src: "ghcr.io/bangumi/ms-timeline"
            dest: "trim21/bangumi-ms-timeline"
            tags: "^(master-.*|v.*)$"
            overwrite: "^(latest|master)$"

          - src: "ghcr.io/bangumi/chii"
            dest: "trim21/bangumi-chii"
            tags: "^(master-.*|v.*)$"
            overwrite: "^(latest|master)$"

          - src: "ghcr.io/trim21/flexget"
            dest: "trim21/flexget"
            tags: ".*"
            overwrite: '^(\d+|\d+\.\d+)$'

          - src: "ghcr.io/trim21/cactbot-importer"
            dest: "trim21/cactbot-importer"
            overwrite: "^latest$"

          - src: "ghcr.io/trim21/bangumi-workers"
            dest: "trim21/bangumi-workers"
            tags: "^(master-.*|v.*)$"
            overwrite: "^(latest|master)$"

          - src: "gcr.io/prysmaticlabs/prysm/beacon-chain"
            dest: "ghcr.io/trim21/prysm-beacon-chain"
            overwrite: "^(stable|latest|latest-alpine)$"
            tags: "^v.*$"

          - src: "gcr.io/prysmaticlabs/prysm/beacon-chain"
            dest: "trim21/prysm-beacon-chain"
            overwrite: "^(stable|latest|latest-alpine)$"

    name: "mirror ${{ matrix.dest }}"

    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: trim21
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: wget https://github.com/trim21/try/releases/latest/download/try_linux_amd64.tar.gz -O- | tar xvz
      - run: wget https://github.com/trim21/imagesync/releases/latest/download/imagesync_linux_amd64.tar.gz -O- | tar xvz

      - if: ${{ matrix.tags }}
        run: |
          ./try --limit=3 --delay=3s -- \
              ./imagesync --src "${{ matrix.src }}" --dest "${{ matrix.dest }}" \
              --tags-pattern '${{ matrix.tags }}' --max-concurrent-tags 4

      - if: ${{ matrix.overwrite }}
        run: |
          ./try --limit=3 --delay=3s -- \
              ./imagesync --src "${{ matrix.src }}" --dest "${{ matrix.dest }}" \
              --overwrite --tags-pattern '${{ matrix.overwrite }}'
