name: pre-commit

#on: ['push']

on:
  push:
    branches:
      - "**"
  schedule:
    # daily on github default branch
    - cron: "0 */3 * * *"

jobs:
  main:
    strategy:
      matrix:
        repo:
          - { repo: Trim21/BGmi, ref: dev }

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Get Latest tools version
        id: get-version
        run: |
          echo "::set-output name=pre-commit::$(curl -sSl https://pypi.org/pypi/pre-commit/json | jq .info.version -r)"
          echo "::set-output name=renovate::$(npm info renovate --json | jq -r .version)"
          # echo "::set-output name=poetry::$(curl -sSl https://pypi.org/pypi/poetry/json | jq .info.version -r)"
          echo "::add-path::$HOME/.local/bin"
          echo "::add-path::$HOME/.poetry/bin"
          PY=$(python --version)
          echo "::set-output name=python::${PY// /_}"

      - uses: actions/cache@v1
        name: Cache Poetry
        with:
          path: ~/.poetry
          key: poetry-itself-${{ steps.get-version.outputs.poetry }}

      - name: Install Poetry
        run: |
          $HOME/.poetry/bin/poetry --version && exit 0
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version ${{ steps.get-version.outputs.poetry }}

      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo.repo }}
          ref: ${{ matrix.repo.ref }}
          path: ${{ matrix.repo.repo }}
          fetch-depth: 1

      - uses: actions/cache@v1
        name: Cache Poetry
        with:
          path: ~/.local
          key: poetry-${{ matrix.repo.repo }}-${{ steps.get-version.outputs.python }}-${{ hashFiles('**/poetry.lock') }}

      - uses: actions/cache@v1
        name: Cache Poetry
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ matrix.repo.repo }}-${{ steps.get-version.outputs.python }}-${{ hashFiles('**/.pre-commit-config.yaml') }}


      - name: Install Dependencies
        working-directory: ./${{ matrix.repo.repo }}
        run: |
          pip install --user --no-deps -q -r <(poetry export -f requirements.txt --dev) || poetry export -f requirements.txt --dev

      - name: check if pre-commit update
        run: |
          set +e
          pre-commit autoupdate
          git diff --exit-code
          RESULT=$?
          if [[ ! $RESULT -eq 0 ]] ; then
            pre-commit run --all-files --show-diff-on-failure
            exit $RESULT
          fi
        working-directory: ./${{ matrix.repo.repo }}
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
