name: qbittorrent

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/qbittorrent.yaml

env:
  QB_VERSION: "release-4.6.5"
  LT_VERSION: "v2.0.10"

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: trim21/qBittorrent
          #          ref: "${{ env.QB_VERSION }}"
          ref: personal-patch

      - uses: actions/checkout@v4
        with:
          ref: "${{ env.LT_VERSION }}"
          repository: arvidn/libtorrent
          path: libtorrent
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.5.*"
          archives: icu qtbase qtdeclarative qtsvg qttools
          cache: true

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ env.QB_VERSION }}-${{ env.LT_VERSION }} # Eg. "some_build-ubuntu-latest"

      - run: >-
          sudo apt-get install -y
          build-essential pkg-config automake libtool git zlib1g-dev
          libssl-dev libgeoip-dev cmake ninja-build

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: "1.83.0"
          platform_version: "22.04"

      - run: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo \
              -D BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }} \
              -D Boost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include\
              -D Boost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib \
              -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build
          sudo cmake --install build
        working-directory: libtorrent

      - run: |
          cmake -B build -G Ninja -D BUILD_SHARED_LIBS=OFF \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D TESTING=OFF -D QT6=ON -D GUI=OFF \
            -D BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }} \
            -D Boost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include\
            -D Boost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - run: cmake --build build

      - uses: actions/upload-artifact@v4
        with:
          path: build/qbittorrent-nox
