name: qbittorrent

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/qbittorrent.yaml
      - qbit-nox.py

env:
  QB_VERSION: "release-5.0.0"
  BOOST_VERSION: "1.86.0"
  QT_VERSION: "6.8.0"

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        lt-version: ["v1.2.19", "v2.0.10"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - run: >-
          sudo apt-get install -y
          build-essential pkg-config automake libtool git zlib1g-dev
          libssl-dev cmake ninja-build
          libglew-dev
          llvm-13 llvm-13-dev libclang-13-dev llvm-13-runtime
          clang-13
          llvm-14 llvm-14-dev libclang-14-dev llvm-14-runtime
          clang-14
          p7zip

      - uses: actions/checkout@v4
        with:
          ref: "${{ matrix.lt-version }}"
          repository: arvidn/libtorrent
          path: src/libtorrent
          submodules: recursive

      - run: mkdir archive -p

      - run: >-
          wget https://download.qt.io/archive/qt/6.8/${{ env.QT_VERSION }}/single/qt-everywhere-src-${{ env.QT_VERSION }}.tar.xz 
          -O archive/qt-everywhere-src-${{ env.QT_VERSION }}.tar.xz -q

      - run: tar x --xz -f archive/qt-everywhere-src-${{ env.QT_VERSION }}.tar.xz qt-everywhere-src-${{ env.QT_VERSION }}
      - run: mv qt-everywhere-src-${{ env.QT_VERSION }} src/qt

      - run: sudo rm ~/.cache/sccache -rf

      ########### qt
      - uses: actions/cache/restore@v4
        id: cache-qt
        with:
          path: ~/.cache/sccache/qt
          key: sccache-${{ env.QT_VERSION }}

      - run: python ./qbit-nox.py qt
        env:
          SCCACHE_DIR: ${{ env.HOME }}/.cache/sccache/qt/

      - uses: actions/cache/save@v4
        with:
          path: ~/.cache/sccache/qt
          key: ${{ steps.cache-qt.outputs.cache-primary-key }}
      ########### qt

      ########### boost
      - uses: actions/cache/restore@v4
        id: cache-boost
        with:
          path: ~/.cache/sccache/boost
          key: sccache-${{ env.BOOST_VERSION }}

      - run: python ./qbit-nox.py boost
        env:
          SCCACHE_DIR: ${{ env.HOME }}/.cache/sccache/boost

      - uses: actions/cache/save@v4
        with:
          path: ~/.cache/sccache/boost
          key: ${{ steps.cache-boost.outputs.cache-primary-key }}
      ########### boost

      - run: >-
          wget https://github.com/boostorg/boost/releases/download/boost-${{ env.BOOST_VERSION }}/boost-${{ env.BOOST_VERSION }}-cmake.7z 
          -O archive/boost.cmake.7z -q

      - run: p7zip -d archive/boost.cmake.7z
      - run: mv boost-${{ env.BOOST_VERSION }} ./src/boost

      - uses: actions/checkout@v4
        with:
          ref: "${{ env.QB_VERSION }}"
          repository: qbittorrent/qBittorrent
          path: src/qBittorrent
          submodules: recursive

      - run: python ./qbit-nox.py lt
        env:
          SCCACHE_DIR: ${{ env.HOME }}/.cache/sccache/lt/

      - run: python ./qbit-nox.py qb
        env:
          SCCACHE_DIR: ${{ env.HOME }}/.cache/sccache/qb/

      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{ matrix.lt-version }}"
          path: |
            build/qb/qbittorrent-nox
