name: qbittorrent

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/qbittorrent.yaml
      - qbit-nox.py

env:
  QB_VERSION: "release-5.0.0"

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        lt-version: ["v1.2.19", "v2.0.10"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - run: >-
          sudo apt-get install -y
          build-essential pkg-config automake libtool git zlib1g-dev
          libssl-dev cmake ninja-build
          libglew-dev
          llvm-13 llvm-13-dev libclang-13-dev llvm-13-runtime
          clang-13
          llvm-14 llvm-14-dev libclang-14-dev llvm-14-runtime
          clang-14
          p7zip

      - uses: actions/checkout@v4
        with:
          ref: "${{ matrix.lt-version }}"
          repository: arvidn/libtorrent
          path: src/libtorrent
          submodules: recursive

      - run: mkdir archive -p

      - run: >-
          wget https://download.qt.io/archive/qt/6.8/6.8.0/single/qt-everywhere-src-6.8.0.tar.xz 
          -O archive/qt-everywhere-src-6.8.0.tar.xz -q

      - run: tar x --xz -f archive/qt-everywhere-src-6.8.0.tar.xz qt-everywhere-src-6.8.0
      - run: mv qt-everywhere-src-6.8.0 src/qt

      - run: >-
          wget https://github.com/boostorg/boost/releases/download/boost-1.86.0/boost-1.86.0-cmake.7z 
          -O archive/boost.cmake.7z -q

      - run: p7zip -d archive/boost.cmake.7z
      - run: mv boost-1.86.0 ./src/boost

      - uses: actions/checkout@v4
        with:
          ref: "${{ env.QB_VERSION }}"
          repository: qbittorrent/qBittorrent
          path: src/qBittorrent
          submodules: recursive

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache
          key: sccache-${{ matrix.lt-version }}

      - run: python ./qbit-nox.py

      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{ matrix.lt-version }}"
          path: |
            build/qb/qbittorrent-nox
