name: qbittorrent

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/qbittorrent.yaml
      - qbit-nox.py

env:
  QB_VERSION: "release-5.0.0"
  LT_VERSION: "v2.0.10"

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: >-
          sudo apt-get install -y
          build-essential pkg-config automake libtool git zlib1g-dev
          libssl-dev cmake ninja-build
          libglew-dev
          llvm-13 llvm-13-dev libclang-13-dev llvm-13-runtime
          clang-13
          llvm-14 llvm-14-dev libclang-14-dev llvm-14-runtime
          clang-14
          pv

      - uses: actions/checkout@v4
        with:
          ref: "${{ env.LT_VERSION }}"
          repository: arvidn/libtorrent
          path: src/libtorrent
          submodules: recursive

      - run: mkdir archive -p

      - run: |
          wget https://download.qt.io/archive/qt/6.8/6.8.0/single/qt-everywhere-src-6.8.0.tar.xz -o archive/qt-everywhere-src-6.8.0.tar.xz 
          pv archive/qt-everywhere-src-6.8.0.tar.xz | tar x --xz -f - -C src/qt

      - run: |
          wget https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.gz -o archive/boost.tar.gz 
          pv archive/boost.tar.gz | tar xzf - -C src/boost

      - run: python ./qbit-nox.py

      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/qb/qbittorrent-nox
