name: sync bucket repos

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/sync-scoop-buckets.yaml
      - mirror_scoop_buckets.mjs
      - package.json
      - yarn.lock
  schedule:
    - cron: "5 3 * * *"

jobs:
  main:
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        repo:
          - { name: scoop, url: "https://github.com/ScoopInstaller/Scoop" }
          - { name: main, url: "https://github.com/ScoopInstaller/Main" }
          - { name: dorado, url: "https://github.com/chawyehsu/dorado.git" }
          - { name: extras, url: "https://github.com/lukesampson/scoop-extras" }
          - { name: "github-gh", url: "https://github.com/cli/scoop-gh" }
          - {
              name: "nerd-fonts",
              url: "https://github.com/matthewjberger/scoop-nerd-fonts",
            }
          - {
              name: versions,
              url: "https://github.com/ScoopInstaller/Versions",
            }
          - { name: backit, url: "https://github.com/batkiz/backit.git" }

    runs-on: ubuntu-latest
    name: "sync ${{ matrix.repo.name }}"

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn

      - run: yarn

      - run: node common/date.mjs

      - name: Repos Cache
        uses: actions/cache@v3
        with:
          path: ./repos/
          key: scoop-bucket-${{ matrix.repo.name }}-2-${{ env.TODAY }}
          restore-keys: |
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D1 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D2 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D3 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y }}-${{ env.M }}-
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.M_1 }}-
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y }}-
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y_1 }}-
            scoop-bucket-${{ matrix.repo.name }}-2-

      - run: wget https://github.com/trim21/try/releases/latest/download/try_linux_amd64.tar.gz -O- | tar xvz

      - name: Run Mirror Script
        run: ./try --delay 1s --limit 10 -- node mirror_scoop_buckets.mjs && exit 0

        env:
          ACCESS_TOKEN: ${{ secrets.GITEE_TOKEN }}
          NAME: ${{ matrix.repo.name }}
          URL: ${{ matrix.repo.url }}
