name: test

on:
  pull_request_target:

jobs:
  my-lint:
    concurrency:
      group: ${{ github.event.pull_request.number }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
      - run: sleep 60
      - run: sleep 60
      - run: sleep 60
      - run: sleep 60
      - run: sleep 60
